import type {
  GraphData,
  GraphNode,
  GraphEdge,
  ScoreData,
  StoryData,
  RefactorData,
  HotSpot,
  GitCommit,
  SampleLoadResponse,
  ScanStatus,
} from '@/types';

const authors = ['张师兄', '李四', '王五', '赵六', '孙七', '钱八'];

function pickAuthor(seed: number): string {
  return authors[seed % authors.length];
}

function makeCommit(
  hash: string,
  date: string,
  author: string,
  message: string,
): GitCommit {
  return { commit_hash: hash, date, author, message };
}

export const mockNodes: GraphNode[] = [
  {
    id: 'f:crawler/main.py',
    name: 'main.py',
    level: 'file',
    file_path: 'crawler/main.py',
    start_line: 1,
    end_line: 280,
    complexity: 18,
    line_count: 280,
    author: pickAuthor(0),
    last_modified: '2025-12-04T10:23:00Z',
    last_commit_hash: 'a1b2c3d',
    test_coverage: 0,
    language: 'python',
  },
  {
    id: 'f:crawler/scraper.py',
    name: 'scraper.py',
    level: 'file',
    file_path: 'crawler/scraper.py',
    start_line: 1,
    end_line: 420,
    complexity: 34,
    line_count: 420,
    author: pickAuthor(1),
    last_modified: '2025-11-20T08:15:00Z',
    last_commit_hash: 'b2c3d4e',
    test_coverage: 12,
    language: 'python',
  },
  {
    id: 'f:crawler/parser.py',
    name: 'parser.py',
    level: 'file',
    file_path: 'crawler/parser.py',
    start_line: 1,
    end_line: 195,
    complexity: 22,
    line_count: 195,
    author: pickAuthor(2),
    last_modified: '2025-10-15T14:00:00Z',
    last_commit_hash: 'c3d4e5f',
    test_coverage: 45,
    language: 'python',
  },
  {
    id: 'f:crawler/db.py',
    name: 'db.py',
    level: 'file',
    file_path: 'crawler/db.py',
    start_line: 1,
    end_line: 320,
    complexity: 16,
    line_count: 320,
    author: pickAuthor(3),
    last_modified: '2025-09-12T11:30:00Z',
    last_commit_hash: 'd4e5f6a',
    test_coverage: 78,
    language: 'python',
  },
  {
    id: 'f:crawler/retry.py',
    name: 'retry.py',
    level: 'file',
    file_path: 'crawler/retry.py',
    start_line: 1,
    end_line: 140,
    complexity: 9,
    line_count: 140,
    author: pickAuthor(4),
    last_modified: '2025-08-30T09:45:00Z',
    last_commit_hash: 'e5f6a7b',
    test_coverage: 65,
    language: 'python',
  },
  {
    id: 'f:crawler/config.py',
    name: 'config.py',
    level: 'file',
    file_path: 'crawler/config.py',
    start_line: 1,
    end_line: 95,
    complexity: 5,
    line_count: 95,
    author: pickAuthor(0),
    last_modified: '2025-07-22T16:20:00Z',
    last_commit_hash: 'f6a7b8c',
    test_coverage: 90,
    language: 'python',
  },
  {
    id: 'f:crawler/logger.py',
    name: 'logger.py',
    level: 'file',
    file_path: 'crawler/logger.py',
    start_line: 1,
    end_line: 60,
    complexity: 3,
    line_count: 60,
    author: pickAuthor(5),
    last_modified: '2025-06-10T12:00:00Z',
    last_commit_hash: 'a7b8c9d',
    test_coverage: 100,
    language: 'python',
  },
  {
    id: 'f:crawler/utils.py',
    name: 'utils.py',
    level: 'file',
    file_path: 'crawler/utils.py',
    start_line: 1,
    end_line: 110,
    complexity: 7,
    line_count: 110,
    author: pickAuthor(1),
    last_modified: '2025-05-18T10:00:00Z',
    last_commit_hash: 'b8c9d0e',
    test_coverage: 50,
    language: 'python',
  },
  {
    id: 'm:crawler.scraper',
    name: 'scraper',
    level: 'module',
    file_path: 'crawler/scraper.py',
    start_line: 1,
    end_line: 420,
    complexity: 34,
    line_count: 420,
    author: pickAuthor(1),
    last_modified: '2025-11-20T08:15:00Z',
    last_commit_hash: 'b2c3d4e',
    test_coverage: 12,
    language: 'python',
    parent_id: 'f:crawler/scraper.py',
  },
  {
    id: 'm:crawler.parser',
    name: 'parser',
    level: 'module',
    file_path: 'crawler/parser.py',
    start_line: 1,
    end_line: 195,
    complexity: 22,
    line_count: 195,
    author: pickAuthor(2),
    last_modified: '2025-10-15T14:00:00Z',
    last_commit_hash: 'c3d4e5f',
    test_coverage: 45,
    language: 'python',
    parent_id: 'f:crawler/parser.py',
  },
  {
    id: 'm:crawler.db',
    name: 'db',
    level: 'module',
    file_path: 'crawler/db.py',
    start_line: 1,
    end_line: 320,
    complexity: 16,
    line_count: 320,
    author: pickAuthor(3),
    last_modified: '2025-09-12T11:30:00Z',
    last_commit_hash: 'd4e5f6a',
    test_coverage: 78,
    language: 'python',
    parent_id: 'f:crawler/db.py',
  },
  {
    id: 'fn:scraper.fetch_page',
    name: 'fetch_page',
    level: 'function',
    file_path: 'crawler/scraper.py',
    start_line: 42,
    end_line: 138,
    complexity: 28,
    line_count: 96,
    author: pickAuthor(1),
    last_modified: '2025-11-20T08:15:00Z',
    last_commit_hash: 'b2c3d4e',
    test_coverage: 0,
    language: 'python',
    parent_id: 'm:crawler.scraper',
  },
  {
    id: 'fn:scraper.parse_html',
    name: 'parse_html',
    level: 'function',
    file_path: 'crawler/scraper.py',
    start_line: 140,
    end_line: 215,
    complexity: 12,
    line_count: 75,
    author: pickAuthor(2),
    last_modified: '2025-10-15T14:00:00Z',
    last_commit_hash: 'c3d4e5f',
    test_coverage: 8,
    language: 'python',
    parent_id: 'm:crawler.scraper',
  },
  {
    id: 'fn:scraper.handle_redirect',
    name: 'handle_redirect',
    level: 'function',
    file_path: 'crawler/scraper.py',
    start_line: 217,
    end_line: 295,
    complexity: 18,
    line_count: 78,
    author: pickAuthor(1),
    last_modified: '2025-09-22T15:40:00Z',
    last_commit_hash: 'c9d0e1f',
    test_coverage: 0,
    language: 'python',
    parent_id: 'm:crawler.scraper',
  },
  {
    id: 'fn:scraper.extract_data',
    name: 'extract_data',
    level: 'function',
    file_path: 'crawler/scraper.py',
    start_line: 297,
    end_line: 360,
    complexity: 14,
    line_count: 63,
    author: pickAuthor(4),
    last_modified: '2025-08-15T13:00:00Z',
    last_commit_hash: 'd0e1f2a',
    test_coverage: 5,
    language: 'python',
    parent_id: 'm:crawler.scraper',
  },
  {
    id: 'fn:parser.clean_text',
    name: 'clean_text',
    level: 'function',
    file_path: 'crawler/parser.py',
    start_line: 12,
    end_line: 48,
    complexity: 8,
    line_count: 36,
    author: pickAuthor(2),
    last_modified: '2025-10-15T14:00:00Z',
    last_commit_hash: 'c3d4e5f',
    test_coverage: 60,
    language: 'python',
    parent_id: 'm:crawler.parser',
  },
  {
    id: 'fn:parser.extract_fields',
    name: 'extract_fields',
    level: 'function',
    file_path: 'crawler/parser.py',
    start_line: 50,
    end_line: 110,
    complexity: 16,
    line_count: 60,
    author: pickAuthor(2),
    last_modified: '2025-10-15T14:00:00Z',
    last_commit_hash: 'c3d4e5f',
    test_coverage: 35,
    language: 'python',
    parent_id: 'm:crawler.parser',
  },
  {
    id: 'fn:parser.validate',
    name: 'validate',
    level: 'function',
    file_path: 'crawler/parser.py',
    start_line: 112,
    end_line: 165,
    complexity: 22,
    line_count: 53,
    author: pickAuthor(2),
    last_modified: '2025-10-15T14:00:00Z',
    last_commit_hash: 'c3d4e5f',
    test_coverage: 25,
    language: 'python',
    parent_id: 'm:crawler.parser',
  },
  {
    id: 'fn:db.connect',
    name: 'connect',
    level: 'function',
    file_path: 'crawler/db.py',
    start_line: 18,
    end_line: 52,
    complexity: 4,
    line_count: 34,
    author: pickAuthor(3),
    last_modified: '2025-09-12T11:30:00Z',
    last_commit_hash: 'd4e5f6a',
    test_coverage: 90,
    language: 'python',
    parent_id: 'm:crawler.db',
  },
  {
    id: 'fn:db.insert',
    name: 'insert',
    level: 'function',
    file_path: 'crawler/db.py',
    start_line: 54,
    end_line: 95,
    complexity: 6,
    line_count: 41,
    author: pickAuthor(3),
    last_modified: '2025-09-12T11:30:00Z',
    last_commit_hash: 'd4e5f6a',
    test_coverage: 80,
    language: 'python',
    parent_id: 'm:crawler.db',
  },
  {
    id: 'fn:db.query',
    name: 'query',
    level: 'function',
    file_path: 'crawler/db.py',
    start_line: 97,
    end_line: 168,
    complexity: 12,
    line_count: 71,
    author: pickAuthor(3),
    last_modified: '2025-09-12T11:30:00Z',
    last_commit_hash: 'd4e5f6a',
    test_coverage: 70,
    language: 'python',
    parent_id: 'm:crawler.db',
  },
  {
    id: 'fn:db.bulk_insert',
    name: 'bulk_insert',
    level: 'function',
    file_path: 'crawler/db.py',
    start_line: 170,
    end_line: 240,
    complexity: 19,
    line_count: 70,
    author: pickAuthor(3),
    last_modified: '2025-09-12T11:30:00Z',
    last_commit_hash: 'd4e5f6a',
    test_coverage: 55,
    language: 'python',
    parent_id: 'm:crawler.db',
  },
  {
    id: 'fn:main.run',
    name: 'run',
    level: 'function',
    file_path: 'crawler/main.py',
    start_line: 22,
    end_line: 145,
    complexity: 32,
    line_count: 123,
    author: pickAuthor(0),
    last_modified: '2025-12-04T10:23:00Z',
    last_commit_hash: 'a1b2c3d',
    test_coverage: 0,
    language: 'python',
    parent_id: 'f:crawler/main.py',
  },
  {
    id: 'fn:main.scheduler',
    name: 'scheduler',
    level: 'function',
    file_path: 'crawler/main.py',
    start_line: 147,
    end_line: 200,
    complexity: 15,
    line_count: 53,
    author: pickAuthor(0),
    last_modified: '2025-11-20T08:15:00Z',
    last_commit_hash: 'b2c3d4e',
    test_coverage: 0,
    language: 'python',
    parent_id: 'f:crawler/main.py',
  },
  {
    id: 'fn:retry.with_backoff',
    name: 'with_backoff',
    level: 'function',
    file_path: 'crawler/retry.py',
    start_line: 15,
    end_line: 78,
    complexity: 11,
    line_count: 63,
    author: pickAuthor(4),
    last_modified: '2025-08-30T09:45:00Z',
    last_commit_hash: 'e5f6a7b',
    test_coverage: 65,
    language: 'python',
    parent_id: 'f:crawler/retry.py',
  },
  {
    id: 'fn:config.load',
    name: 'load',
    level: 'function',
    file_path: 'crawler/config.py',
    start_line: 12,
    end_line: 45,
    complexity: 5,
    line_count: 33,
    author: pickAuthor(0),
    last_modified: '2025-07-22T16:20:00Z',
    last_commit_hash: 'f6a7b8c',
    test_coverage: 95,
    language: 'python',
    parent_id: 'f:crawler/config.py',
  },
  {
    id: 'fn:utils.sanitize',
    name: 'sanitize',
    level: 'function',
    file_path: 'crawler/utils.py',
    start_line: 8,
    end_line: 38,
    complexity: 6,
    line_count: 30,
    author: pickAuthor(1),
    last_modified: '2025-05-18T10:00:00Z',
    last_commit_hash: 'b8c9d0e',
    test_coverage: 50,
    language: 'python',
    parent_id: 'f:crawler/utils.py',
  },
  {
    id: 'fn:utils.hash_url',
    name: 'hash_url',
    level: 'function',
    file_path: 'crawler/utils.py',
    start_line: 40,
    end_line: 62,
    complexity: 4,
    line_count: 22,
    author: pickAuthor(1),
    last_modified: '2025-05-18T10:00:00Z',
    last_commit_hash: 'b8c9d0e',
    test_coverage: 60,
    language: 'python',
    parent_id: 'f:crawler/utils.py',
  },
  {
    id: 'fn:logger.setup',
    name: 'setup',
    level: 'function',
    file_path: 'crawler/logger.py',
    start_line: 5,
    end_line: 32,
    complexity: 3,
    line_count: 27,
    author: pickAuthor(5),
    last_modified: '2025-06-10T12:00:00Z',
    last_commit_hash: 'a7b8c9d',
    test_coverage: 100,
    language: 'python',
    parent_id: 'f:crawler/logger.py',
  },
  {
    id: 'fn:logger.log_error',
    name: 'log_error',
    level: 'function',
    file_path: 'crawler/logger.py',
    start_line: 34,
    end_line: 56,
    complexity: 2,
    line_count: 22,
    author: pickAuthor(5),
    last_modified: '2025-06-10T12:00:00Z',
    last_commit_hash: 'a7b8c9d',
    test_coverage: 100,
    language: 'python',
    parent_id: 'f:crawler/logger.py',
  },
];

export const mockEdges: GraphEdge[] = [
  { source: 'f:crawler/main.py', target: 'f:crawler/scraper.py', call_type: 'direct', call_count: 5 },
  { source: 'f:crawler/main.py', target: 'f:crawler/config.py', call_type: 'direct', call_count: 3 },
  { source: 'f:crawler/main.py', target: 'f:crawler/logger.py', call_type: 'direct', call_count: 8 },
  { source: 'f:crawler/main.py', target: 'f:crawler/retry.py', call_type: 'direct', call_count: 2 },
  { source: 'f:crawler/scraper.py', target: 'f:crawler/parser.py', call_type: 'direct', call_count: 12 },
  { source: 'f:crawler/scraper.py', target: 'f:crawler/db.py', call_type: 'direct', call_count: 6 },
  { source: 'f:crawler/scraper.py', target: 'f:crawler/retry.py', call_type: 'direct', call_count: 4 },
  { source: 'f:crawler/scraper.py', target: 'f:crawler/utils.py', call_type: 'direct', call_count: 7 },
  { source: 'f:crawler/parser.py', target: 'f:crawler/utils.py', call_type: 'direct', call_count: 3 },
  { source: 'f:crawler/db.py', target: 'f:crawler/logger.py', call_type: 'direct', call_count: 2 },
  { source: 'f:crawler/retry.py', target: 'f:crawler/logger.py', call_type: 'direct', call_count: 1 },
  { source: 'f:crawler/config.py', target: 'f:crawler/logger.py', call_type: 'direct', call_count: 1 },
  { source: 'f:crawler/main.py', target: 'f:crawler/db.py', call_type: 'indirect', call_count: 1 },
  { source: 'f:crawler/parser.py', target: 'f:crawler/db.py', call_type: 'indirect', call_count: 2 },
  { source: 'f:crawler/utils.py', target: 'f:crawler/logger.py', call_type: 'indirect', call_count: 1 },
  { source: 'f:crawler/scraper.py', target: 'f:crawler/config.py', call_type: 'indirect', call_count: 2 },
  { source: 'f:crawler/main.py', target: 'f:crawler/scraper.py', call_type: 'callback', call_count: 3 },
  { source: 'f:crawler/main.py', target: 'f:crawler/db.py', call_type: 'callback', call_count: 1 },
  { source: 'f:crawler/scraper.py', target: 'f:crawler/parser.py', call_type: 'callback', call_count: 4 },
  { source: 'f:crawler/scraper.py', target: 'f:crawler/retry.py', call_type: 'callback', call_count: 2 },
  { source: 'f:crawler/parser.py', target: 'f:crawler/logger.py', call_type: 'callback', call_count: 1 },
  { source: 'f:crawler/db.py', target: 'f:crawler/config.py', call_type: 'callback', call_count: 1 },
  { source: 'f:crawler/scraper.py', target: 'f:crawler/parser.py', call_type: 'dataflow', call_count: 8 },
  { source: 'f:crawler/parser.py', target: 'f:crawler/db.py', call_type: 'dataflow', call_count: 5 },
  { source: 'f:crawler/scraper.py', target: 'f:crawler/db.py', call_type: 'dataflow', call_count: 3 },
  { source: 'f:crawler/main.py', target: 'f:crawler/scraper.py', call_type: 'dataflow', call_count: 2 },
  { source: 'f:crawler/db.py', target: 'f:crawler/scraper.py', call_type: 'dataflow', call_count: 1 },
  { source: 'f:crawler/main.py', target: 'f:crawler/utils.py', call_type: 'dataflow', call_count: 1 },
  { source: 'fn:main.run', target: 'fn:scraper.fetch_page', call_type: 'direct', call_count: 10 },
  { source: 'fn:main.run', target: 'fn:db.connect', call_type: 'direct', call_count: 1 },
  { source: 'fn:main.run', target: 'fn:config.load', call_type: 'direct', call_count: 2 },
  { source: 'fn:main.run', target: 'fn:logger.setup', call_type: 'direct', call_count: 1 },
  { source: 'fn:main.scheduler', target: 'fn:scraper.fetch_page', call_type: 'direct', call_count: 5 },
  { source: 'fn:main.scheduler', target: 'fn:retry.with_backoff', call_type: 'direct', call_count: 2 },
  { source: 'fn:scraper.fetch_page', target: 'fn:scraper.parse_html', call_type: 'direct', call_count: 8 },
  { source: 'fn:scraper.fetch_page', target: 'fn:retry.with_backoff', call_type: 'direct', call_count: 4 },
  { source: 'fn:scraper.fetch_page', target: 'fn:utils.sanitize', call_type: 'direct', call_count: 2 },
  { source: 'fn:scraper.parse_html', target: 'fn:scraper.extract_data', call_type: 'direct', call_count: 6 },
  { source: 'fn:scraper.parse_html', target: 'fn:scraper.handle_redirect', call_type: 'direct', call_count: 3 },
  { source: 'fn:scraper.extract_data', target: 'fn:parser.clean_text', call_type: 'direct', call_count: 5 },
  { source: 'fn:scraper.extract_data', target: 'fn:parser.extract_fields', call_type: 'direct', call_count: 5 },
  { source: 'fn:parser.extract_fields', target: 'fn:parser.validate', call_type: 'direct', call_count: 4 },
  { source: 'fn:parser.validate', target: 'fn:db.insert', call_type: 'direct', call_count: 3 },
  { source: 'fn:db.query', target: 'fn:db.bulk_insert', call_type: 'direct', call_count: 2 },
  { source: 'fn:db.insert', target: 'fn:db.bulk_insert', call_type: 'direct', call_count: 1 },
  { source: 'fn:scraper.fetch_page', target: 'fn:logger.log_error', call_type: 'callback', call_count: 2 },
  { source: 'fn:scraper.parse_html', target: 'fn:utils.hash_url', call_type: 'callback', call_count: 1 },
  { source: 'fn:db.bulk_insert', target: 'fn:db.query', call_type: 'dataflow', call_count: 2 },
  { source: 'fn:scraper.fetch_page', target: 'fn:scraper.parse_html', call_type: 'dataflow', call_count: 6 },
  { source: 'fn:scraper.extract_data', target: 'fn:db.insert', call_type: 'dataflow', call_count: 4 },
  { source: 'fn:parser.validate', target: 'fn:db.bulk_insert', call_type: 'dataflow', call_count: 1 },
];

export const mockHotSpots: HotSpot[] = [
  {
    rank: 1,
    file_path: 'crawler/main.py',
    function_name: 'run',
    severity: 'extreme',
    severity_color: '#F44336',
    complexity: 32,
    suggestion: '拆分入口函数，将调度逻辑下沉到 CrawlerScheduler 类；考虑引入协程并发',
  },
  {
    rank: 2,
    file_path: 'crawler/scraper.py',
    function_name: 'fetch_page',
    severity: 'extreme',
    severity_color: '#F44336',
    complexity: 28,
    suggestion: '提取重试策略、HTML 解析、Header 注入为独立函数；引入请求上下文对象',
  },
  {
    rank: 3,
    file_path: 'crawler/parser.py',
    function_name: 'validate',
    severity: 'high',
    severity_color: '#FF9800',
    complexity: 22,
    suggestion: '使用 schema 库（如 pydantic）替换手写校验逻辑',
  },
  {
    rank: 4,
    file_path: 'crawler/scraper.py',
    function_name: 'handle_redirect',
    severity: 'high',
    severity_color: '#FF9800',
    complexity: 18,
    suggestion: '递归逻辑改为循环 + 最大跳数限制，避免栈溢出',
  },
  {
    rank: 5,
    file_path: 'crawler/db.py',
    function_name: 'bulk_insert',
    severity: 'high',
    severity_color: '#FF9800',
    complexity: 19,
    suggestion: '使用 executemany 或 COPY 协议；拆出错误重试逻辑',
  },
  {
    rank: 6,
    file_path: 'crawler/main.py',
    function_name: 'scheduler',
    severity: 'medium',
    severity_color: '#FFC107',
    complexity: 15,
    suggestion: '改用 APScheduler 等成熟调度库',
  },
  {
    rank: 7,
    file_path: 'crawler/scraper.py',
    function_name: 'extract_data',
    severity: 'medium',
    severity_color: '#FFC107',
    complexity: 14,
    suggestion: '拆分为字段级提取器；引入 xpath/css selector 配置化',
  },
  {
    rank: 8,
    file_path: 'crawler/db.py',
    function_name: 'query',
    severity: 'medium',
    severity_color: '#FFC107',
    complexity: 12,
    suggestion: '提取 SQL 构造为查询构建器；增加查询超时',
  },
  {
    rank: 9,
    file_path: 'crawler/retry.py',
    function_name: 'with_backoff',
    severity: 'low',
    severity_color: '#4CAF50',
    complexity: 11,
    suggestion: '增加 jitter 抖动；支持自定义异常白名单',
  },
  {
    rank: 10,
    file_path: 'crawler/parser.py',
    function_name: 'extract_fields',
    severity: 'low',
    severity_color: '#4CAF50',
    complexity: 16,
    suggestion: '用 dataclass 替代 tuple 返回值',
  },
];

export const mockScoreData: ScoreData = {
  scan_id: 'mock-scan-001',
  total_score: 37,
  rating: '屎山警告',
  rating_color: '#FF9800',
  dimensions: {
    complexity: 42,
    duplication: 28,
    comment: 18,
    author_centrality: 35,
    test_coverage: 22,
  },
  hot_spots: mockHotSpots,
};

const timelineFn1: GitCommit[] = [
  makeCommit('b2c3d4e', '2025-11-20T08:15:00Z', '李四', '重构 fetch_page 但保留了太多分支'),
  makeCommit('a8b9c0d', '2025-08-15T13:00:00Z', '赵六', '临时方案，下周重构'),
  makeCommit('f1e2d3c', '2025-03-12T10:30:00Z', '王五', '修复登录超时问题'),
  makeCommit('9a8b7c6', '2024-11-05T16:00:00Z', '张师兄', '初版爬虫实现'),
  makeCommit('5d4e3f2', '2024-06-22T11:45:00Z', '张师兄', '第一次提交爬虫框架'),
];

const timelineFn2: GitCommit[] = [
  makeCommit('a1b2c3d', '2025-12-04T10:23:00Z', '张师兄', '主入口添加了硬编码配置项'),
  makeCommit('b2c3d4e', '2025-11-20T08:15:00Z', '李四', '重构 main 调度'),
  makeCommit('7e8f9a0', '2025-07-18T09:00:00Z', '孙七', 'main 流程加日志'),
  makeCommit('1b2c3d4', '2025-02-14T14:20:00Z', '钱八', '拆分入口函数'),
  makeCommit('5f6a7b8', '2024-08-30T15:00:00Z', '张师兄', '初版主程序'),
];

const timelineFn3: GitCommit[] = [
  makeCommit('c3d4e5f', '2025-10-15T14:00:00Z', '王五', 'parser 校验逻辑加强'),
  makeCommit('8c9d0e1', '2025-06-22T11:00:00Z', '王五', 'extract_fields 重构'),
  makeCommit('2d3e4f5', '2024-12-10T10:00:00Z', '王五', 'parser 模块化'),
  makeCommit('6a7b8c9', '2024-05-05T13:30:00Z', '张师兄', 'parser 初始实现'),
];

export const mockStoryData: StoryData = {
  node_id: 'fn:scraper.fetch_page',
  summary: 'fetch_page 是整个爬虫的核心，但因反复"临时方案"已演化为屎山',
  timeline: timelineFn1,
  narrative:
    'fetch_page 函数最早由 <code class="hl">张师兄</code> 在 2024 年 6 月创建，初版只是一个简单的 HTTP GET。' +
    '在 2024 年 11 月的 commit <code class="code">9a8b7c6</code> 中，王五为了处理登录态注入了 cookie 处理逻辑。' +
    '<br/><br/>' +
    '2025 年 3 月的 commit <code class="code">f1e2d3c</code> 出现了经典的 <code class="danger">"临时方案"</code> 注释，' +
    '李四直接在函数内增加了三层嵌套 if-else 处理超时重试。' +
    '<br/><br/>' +
    '到了 2025 年 8 月，赵六在 <code class="code">a8b9c0d</code> 中又叠加了 User-Agent 轮换和代理池，' +
    '函数膨胀到 96 行、圈复杂度达到 <code class="danger">28</code>。' +
    '<br/><br/>' +
    '2025 年 11 月，李四的 commit <code class="code">b2c3d4e</code> 尝试"重构"，但保留了所有分支，' +
    '复杂度反而上升到 28。当前该函数完全没有测试覆盖（0%），是项目最大的风险点。',
  model: 'mock-llm',
  generated_at: '2026-06-16T12:00:00Z',
};

export const mockStoryData2: StoryData = {
  node_id: 'fn:main.run',
  summary: 'main.run 是项目入口，由张师兄长期维护，已积累大量分支',
  timeline: timelineFn2,
  narrative:
    'main.run 是项目的总入口，最早由 <code class="hl">张师兄</code> 在 2024 年 8 月创建。' +
    '在 2025 年 2 月，钱八曾尝试拆分入口函数（<code class="code">1b2c3d4</code>），但后续又被合并回单一函数。' +
    '<br/><br/>' +
    '<code class="danger">2025 年 12 月</code> 的 commit <code class="code">a1b2c3d</code> 中，' +
    '张师兄加入了硬编码的配置项，导致该函数复杂度飙升至 32。' +
    '<br/><br/>' +
    '建议：立即将调度逻辑下沉到独立类，引入配置文件加载。',
  model: 'mock-llm',
  generated_at: '2026-06-16T12:00:00Z',
};

export const mockStoryData3: StoryData = {
  node_id: 'fn:parser.validate',
  summary: 'parser.validate 长期由王五独自维护，注释严重不足',
  timeline: timelineFn3,
  narrative:
    'parser.validate 模块由 <code class="hl">王五</code> 主导开发，从 2024 年 5 月至今所有相关 commit 均出自他手。' +
    '这种 <code class="danger">"一人包办"</code> 的模式导致 <code class="hl">作者集中度</code> 指标异常。' +
    '<br/><br/>' +
    '2024 年 12 月的 <code class="code">2d3e4f5</code> 完成了模块化拆分，但 2025 年 6 月的 <code class="code">8c9d0e1</code> 又回退到单文件。' +
    '<br/><br/>' +
    '建议：引入 schema 库（pydantic）并补全测试覆盖。',
  model: 'mock-llm',
  generated_at: '2026-06-16T12:00:00Z',
};

export const mockRefactorData: RefactorData = {
  node_id: 'fn:scraper.fetch_page',
  suggestion:
    '将 fetch_page 拆分为四个职责清晰的小函数：build_request_headers、execute_with_retry、parse_response、validate_response。' +
    '引入 RequestContext 上下文对象传递状态，消除全局变量依赖。',
  priority: 'high',
  diff:
    '- def fetch_page(url, retries=3):\n' +
    '-     headers = {"User-Agent": random_ua()}\n' +
    '-     for i in range(retries):\n' +
    '-         try:\n' +
    '-             r = requests.get(url, headers=headers, timeout=10)\n' +
    '-             if r.status_code == 200:\n' +
    '-                 ...\n' +
    '+ def fetch_page(url: str, ctx: RequestContext) -> Response:\n' +
    '+     headers = build_request_headers(ctx)\n' +
    '+     return execute_with_retry(\n' +
    '+         lambda: requests.get(url, headers=headers, timeout=ctx.timeout),\n' +
    '+         retries=ctx.retries,\n' +
    '+         backoff=ctx.backoff,\n' +
    '+     )',
  estimated_reduction: '圈复杂度 28 → 8（-71%），行数 96 → 42（-56%）',
};

export const mockGraphData: GraphData = {
  scan_id: 'mock-scan-001',
  level: 'function',
  nodes: mockNodes,
  edges: mockEdges,
};

export const mockScanStatus: ScanStatus = {
  scan_id: 'mock-scan-001',
  progress: 8,
  total: 8,
  current_file: 'crawler/logger.py',
  status: 'done',
};

export const mockSampleLoad: SampleLoadResponse = {
  scan_id: 'mock-scan-001',
  project_name: '祖传 Python 爬虫',
  project_path: 'sample-project/crawler',
  total_files: 8,
};
